name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib
  - setuptools
  - seaborn
  - scipy
  - pytest

    # Pip-only installs
  - pip:
      - sphinx-autoapi

